grails-app/domain/com/nuclearreactor/accounts/Account.groovy
package com.nuclearreactor.accounts

import com.nuclearreactor.users.User

/**
 * Representation of an Account in weservice
 *
 * @author <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a>
 * @version 27/11/2014 - <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a> - First Version
 * @since 27/11/2014 Copyright © All Rights Reserved.
 */
class Account {

    String firstName
    String lastName
    String preferredLocale
    String identificationNumber
    String address
    String phoneNumber

    byte[] avatarImage

    AccountType accountType

    User user

    static constraints = {
        firstName nullable: false, blank: false
        lastName blank: false, nullable: true
        preferredLocale blank: false, nullable: false
        identificationNumber nullable: true, blank: false
        address nullable: true
        phoneNumber nullable: true
        user nullable: true
        avatarImage nullable: true
        accountType nullable: false
    }

    static mapping = {
        tablePerHierarchy false
    }


}

public enum AccountType {
    Principal("Pri"),
    Customer("Cus");

    final String id

    AccountType(String id) {
        this.id = id
    }

    String toString() {
        id
    }

    String getKey() {
        name()
    }
}

grails-app/domain/com/nuclearreactor/accounts/CompanyAccount.groovy
package com.nuclearreactor.accounts

/**
 * Representation of a Company account in the system
 *
 * @author <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a>
 * @version 28/11/2014 - <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a> - First Version
 * @since 28/11/2014 Copyright © All Rights Reserved.
 */
class CompanyAccount extends Account{

    String description

    static constraints = {
        description nullable: true
    }
}

grails-app/domain/com/nuclearreactor/alerts/Alert.groovy
package com.nuclearreactor.alerts

import com.nuclearreactor.reactor.NuclearReactor

/**
 * Alert Entity
 */
class Alert {

    AlertType type
    String message
    Date alertDate = new Date()

    static belongsTo = [
            nuclearReactor : NuclearReactor
    ]
    static constraints = {
        type nullable: false
        message nullable: false
        nuclearReactor nullable: false
        alertDate nullable: false
    }
}

grails-app/domain/com/nuclearreactor/alerts/AlertType.groovy
package com.nuclearreactor.alerts

/**
 * Created by diegoamaya on 3/09/15.
 */
enum AlertType {
    Information("I"),
    Warning("W"),
    Danger("D")

    private final String type;

    public AlertType(String type){
        this.type = type
    }

    public static AlertType fromStringToEnum(String type){
        for(AlertType value: values()){
            if(type.equals(value.type)){
                return value
            }
        }
    }

    public String getState(){
        return state;
    }
}

grails-app/domain/com/nuclearreactor/alerts/AlertsConfiguration.groovy
package com.nuclearreactor.alerts

import com.nuclearreactor.reactor.NuclearReactor

class AlertsConfiguration {

    //TEMPERATURE CONFIGURATION
    Float infoMaxTempPercentage
    Float warningMaxTempPercentage
    Float dangerMaxTempPercentage

    //CHANNEL CONFIGURATION
    Boolean sendWebSocketAlert = true
    Boolean sendEmailAlert = true
    Boolean sendRestAlert = true

    //USER CONFIGURATION
    Boolean sendAlertToOperator
    Boolean sendAlertToAdministrator

    static belongsTo = [
            nuclearReactor : NuclearReactor
    ]

    static constraints = {
        infoMaxTempPercentage nullable: false, min: 0.0F
        warningMaxTempPercentage nullable: false, min: 0.0F
        dangerMaxTempPercentage nullable: false, min: 0.0F
        nuclearReactor nullable: false
        sendWebSocketAlert nullable: false
        sendEmailAlert nullable: false
        sendAlertToOperator nullable: false
        sendAlertToAdministrator nullable: false
        sendRestAlert nullable: false
    }
}

grails-app/domain/com/nuclearreactor/audits/Audits.groovy
package com.nuclearreactor.audits

import com.nuclearreactor.reactor.NuclearReactor

class Audits {

    String user
    OperationType operation
    Date date

    static belongsTo = [
            nuclearReactor : NuclearReactor
    ]

    static constraints = {
        user nullable: true
        operation nullable: false
        date nullable: false
        nuclearReactor nullable: false
    }


}
enum OperationType{
    SET_RODS_STATE,
    SET_VALVE_STATE,
    SET_HEATER_STATE,
    GET_REACTOR_INFO,
    GET_TEMP_INFO
}

grails-app/domain/com/nuclearreactor/audits/RequestHistory.groovy
package com.nuclearreactor.audits

/**
 * Created by hernan on 23/11/15.
 */
class RequestHistory {

    String request
    Date requestDate
    String requestType

    static constraints = {

        request nullable: false, blank: false
        requestDate nullable: false, blank: false
        requestType nullable: false, blank: false

    }


}

grails-app/domain/com/nuclearreactor/reactor/CoolantSystem.groovy
package com.nuclearreactor.reactor

/**
 * Representation of a Coolant System
 *
 * @author <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a>
 * @version 17/08/2015 - <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a> - First Version
 * @since 17/08/2015.
 */
class CoolantSystem {

    Float humidityPercentage

    Double currentTemperature
    Double idealTemperature

    //Galones/Minuto
    Double waterPressure

    static belongsTo = [nuclearReactor : NuclearReactor]


    static constraints = {
        humidityPercentage nullable: false, min: 0.0F, max: 1.0F
        currentTemperature nullable: false
        waterPressure nullable: true
        idealTemperature nullable: false
    }
}

grails-app/domain/com/nuclearreactor/reactor/NuclearReactor.groovy
package com.nuclearreactor.reactor

import com.nuclearreactor.accounts.CompanyAccount
import com.nuclearreactor.alerts.AlertsConfiguration

/**
 * Representation of a Nuclear Reactor
 *
 * @author <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a>
 * @version 17/08/2015 - <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a> - First Version
 * @since 17/08/2015
 */
class NuclearReactor {

    String code

    //Bomba
    PumpState pumpState
    //Barras
    RodsState rodsState
    //Resistencia/Calentador
    HeaterState heaterState

    Date lastUpdate


    static hasOne = [
            coolantSystem: CoolantSystem,
            configuration: NuclearReactorConfiguration,
            alertsConfiguration: AlertsConfiguration

    ]

    static hasMany = [
            valves : Valve
    ]

    static belongsTo = [
            company: CompanyAccount
    ]

    static fetchMode = [
            configuration: 'eager',
            coolantSystem: 'eager',
            alertsConfiguration: 'lazy'
    ]

    static constraints = {
        company nullable: false
        code nullable: false, blank: false
        lastUpdate nullable: true
        pumpState nullable: true
        rodsState nullable: true
        heaterState nullable: true
        configuration nullable: true
        valves nullable: true
        alertsConfiguration nullable: true
    }

    @Override
    public String toString() {
        return "NuclearReactor{" +
                "id=" + id +
                ", code='" + code + '\'' +
                ", pumpState=" + pumpState +
                ", rodsState=" + rodsState +
                ", heaterState=" + heaterState +
                ", lastUpdate=" + lastUpdate +
                ", version=" + version +
                ", valves=" + valves +
                ", alertsConfiguration=" + alertsConfiguration +
                ", coolantSystem=" + coolantSystem +
                ", configuration=" + configuration +
                ", company=" + company +
                '}';
    }
}
enum RodsState{
    Up("Arriba"),
    Down("Abajo")

    private final String state;

    public RodsState(String state){
        this.state = state
    }

    public static RodsState fromStringToEnum(String state){
        for(RodsState value: values()){
            if(state.equals(value.state)){
                return value
            }
        }
    }

    public String getState(){
        return state
    }
}
enum PumpState {
    Active("ON"),
    Inactive("OFF")

    private final String state;

    public PumpState(String state) {
        this.state = state
    }

    public static PumpState fromStringToEnum(String state) {
        for (PumpState value : values()) {
            if (state.equals(value.state)) {
                return value
            }
        }
    }
    public String getState(){
        return state;
    }
}

enum HeaterState{
    Active("ON"),
    Inactive("OFF")

    private final String state;

    public HeaterState(String state){
        this.state = state
    }

    public static HeaterState fromStringToEnum(String state){
        for(HeaterState value: values()){
            if(state.equals(value.state)){
                return value
            }
        }
    }

public String getState(){
    return state;
}
}

grails-app/domain/com/nuclearreactor/reactor/NuclearReactorConfiguration.groovy
package com.nuclearreactor.reactor

class NuclearReactorConfiguration {

    String getReactorInfoURL
    String getTemperatureURL
    String setValveStateURL
    String setRodsStateURL
    String setPumpStateURL
    String setHeaterStateURL



    static belongsTo = [
            nuclearReactor : NuclearReactor
    ]
    static constraints = {
        getReactorInfoURL nullable: true, blank: false
        getTemperatureURL nullable: true, blank: false
        setValveStateURL nullable: true, blank: false
        setRodsStateURL nullable: true, blank: false
        setPumpStateURL nullable: true, blank: false
        setHeaterStateURL nullable: true, blank: false
        nuclearReactor nullable: false
    }

}

grails-app/domain/com/nuclearreactor/reactor/NuclearReactorHistory.groovy
package com.nuclearreactor.reactor

/**
 * Created by diegoamaya on 29/08/15.
 */
class NuclearReactorHistory {

    String code

    Date lastUpdate

    //Bomba
    PumpState pumpState
    //Barras
    RodsState rodsState
    //Resistencia/Calentador
    HeaterState heaterState

    Date date

    Float humidityPercentage

    Double currentTemperature
    Double idealTemperature

    String valvesState

    static constraints = {
        valvesState nullable: false, blank: false
        idealTemperature nullable: false
        currentTemperature nullable: false
        humidityPercentage nullable: true
        rodsState nullable: false
        pumpState nullable: false
        heaterState nullable: true
        lastUpdate nullable: false
        date nullable: false
        code nullable: false
    }
    static belongsTo = [
            nuclearReactor : NuclearReactor
    ]

    static fetchMode = [
            nuclearReactor : 'lazy'
    ]
}

grails-app/domain/com/nuclearreactor/reactor/Valve.groovy
package com.nuclearreactor.reactor

/**
 * Representation of Valve that belongs to the reactor
 *
 * @author <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a>
 * @version 17/08/2015 - <a href="emailto:diegoaam_02@hotmail.com">Diego Amaya</a> - First Version
 * @since 17/08/2015.
 */
class Valve {

    ValveState state
    String identifier

    static belongsTo = [
            nuclearReactor : NuclearReactor
    ]

    static constraints = {
        state nullable: false
        identifier nullable: false, unique: true, blank: false
        nuclearReactor nullable: false
    }
}
enum ValveState{
    Open("ON"),
    Closed("OFF")

    private final String state

    public ValveState(String state){
        this.state = state
    }

    public static ValveState fromStringToEnum(String state){
        for(ValveState value: values()){
            if(state.equals(value.state)){
                return value
            }
        }
    }

    public String getState(){
        return state
    }
}

grails-app/controllers/com/nuclearreactor/reactor/NuclearReactorConfigurationController.groovy
package com.nuclearreactor.reactor

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class NuclearReactorConfigurationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def index(Integer max) {
        redirect(action: 'show', id: NuclearReactor.findByCode("2XD1AS").configuration.id)
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def show(NuclearReactorConfiguration nuclearReactorConfigurationInstance) {
        respond nuclearReactorConfigurationInstance
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def edit(NuclearReactorConfiguration nuclearReactorConfigurationInstance) {
        respond nuclearReactorConfigurationInstance
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    @Transactional
    def update(NuclearReactorConfiguration nuclearReactorConfigurationInstance) {
        if (nuclearReactorConfigurationInstance == null) {
            notFound()
            return
        }

        if (nuclearReactorConfigurationInstance.hasErrors()) {
            respond nuclearReactorConfigurationInstance.errors, view: 'edit'
            return
        }

        nuclearReactorConfigurationInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'NuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration'), nuclearReactorConfigurationInstance.id])
                redirect nuclearReactorConfigurationInstance
            }
            '*' { respond nuclearReactorConfigurationInstance, [status: OK] }
        }
    }
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'nuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/nuclearreactor/reactor/NuclearReactorController.groovy
package com.nuclearreactor.reactor

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class NuclearReactorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def index(Integer max) {
        redirect(action: 'show', id: NuclearReactor.findByCode("2XD1AS").id)
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def show(NuclearReactor nuclearReactorInstance) {
        respond nuclearReactorInstance
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def edit(NuclearReactor nuclearReactorInstance) {
        respond nuclearReactorInstance
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    @Transactional
    def update(NuclearReactor nuclearReactorInstance) {
        if (nuclearReactorInstance == null) {
            notFound()
            return
        }

        if (nuclearReactorInstance.hasErrors()) {
            respond nuclearReactorInstance.errors, view: 'edit'
            return
        }

        nuclearReactorInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'NuclearReactor.label', default: 'NuclearReactor'), nuclearReactorInstance.id])
                redirect nuclearReactorInstance
            }
            '*' { respond nuclearReactorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(NuclearReactor nuclearReactorInstance) {

        if (nuclearReactorInstance == null) {
            notFound()
            return
        }

        nuclearReactorInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'NuclearReactor.label', default: 'NuclearReactor'), nuclearReactorInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'nuclearReactor.label', default: 'NuclearReactor'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/nuclearReactor/_form.gsp
<%@ page import="com.nuclearreactor.reactor.NuclearReactor" %>



<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'company', 'error')} required">
	<label for="company">
		<g:message code="nuclearReactor.company.label" default="Company" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="company" name="company.id" from="${com.nuclearreactor.accounts.CompanyAccount.list()}" optionKey="id" required="" value="${nuclearReactorInstance?.company?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'code', 'error')} required">
	<label for="code">
		<g:message code="nuclearReactor.code.label" default="Code" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="code" required="" value="${nuclearReactorInstance?.code}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'lastUpdate', 'error')} ">
	<label for="lastUpdate">
		<g:message code="nuclearReactor.lastUpdate.label" default="Last Update" />
		
	</label>
	<g:datePicker name="lastUpdate" precision="day"  value="${nuclearReactorInstance?.lastUpdate}" default="none" noSelection="['': '']" />

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'pumpState', 'error')} ">
	<label for="pumpState">
		<g:message code="nuclearReactor.pumpState.label" default="Pump State" />
		
	</label>
	<g:select name="pumpState" from="${com.nuclearreactor.reactor.PumpState?.values()}" keys="${com.nuclearreactor.reactor.PumpState.values()*.name()}" value="${nuclearReactorInstance?.pumpState?.name()}"  noSelection="['': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'rodsState', 'error')} ">
	<label for="rodsState">
		<g:message code="nuclearReactor.rodsState.label" default="Rods State" />
		
	</label>
	<g:select name="rodsState" from="${com.nuclearreactor.reactor.RodsState?.values()}" keys="${com.nuclearreactor.reactor.RodsState.values()*.name()}" value="${nuclearReactorInstance?.rodsState?.name()}"  noSelection="['': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'heaterState', 'error')} ">
	<label for="heaterState">
		<g:message code="nuclearReactor.heaterState.label" default="Heater State" />
		
	</label>
	<g:select name="heaterState" from="${com.nuclearreactor.reactor.HeaterState?.values()}" keys="${com.nuclearreactor.reactor.HeaterState.values()*.name()}" value="${nuclearReactorInstance?.heaterState?.name()}"  noSelection="['': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'configuration', 'error')} ">
	<label for="configuration">
		<g:message code="nuclearReactor.configuration.label" default="Configuration" />
		
	</label>
	<g:select id="configuration" name="configuration.id" from="${com.nuclearreactor.reactor.NuclearReactorConfiguration.list()}" optionKey="id" value="${nuclearReactorInstance?.configuration?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'valves', 'error')} ">
	<label for="valves">
		<g:message code="nuclearReactor.valves.label" default="Valves" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${nuclearReactorInstance?.valves?}" var="v">
    <li><g:link controller="valve" action="show" id="${v.id}">${v?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="valve" action="create" params="['nuclearReactor.id': nuclearReactorInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'valve.label', default: 'Valve')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'alertsConfiguration', 'error')} ">
	<label for="alertsConfiguration">
		<g:message code="nuclearReactor.alertsConfiguration.label" default="Alerts Configuration" />
		
	</label>
	<g:select id="alertsConfiguration" name="alertsConfiguration.id" from="${com.nuclearreactor.alerts.AlertsConfiguration.list()}" optionKey="id" value="${nuclearReactorInstance?.alertsConfiguration?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorInstance, field: 'coolantSystem', 'error')} required">
	<label for="coolantSystem">
		<g:message code="nuclearReactor.coolantSystem.label" default="Coolant System" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="coolantSystem" name="coolantSystem.id" from="${com.nuclearreactor.reactor.CoolantSystem.list()}" optionKey="id" required="" value="${nuclearReactorInstance?.coolantSystem?.id}" class="many-to-one"/>

</div>

grails-app/views/nuclearReactor/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'nuclearReactor.label', default: 'NuclearReactor')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-nuclearReactor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-nuclearReactor" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${nuclearReactorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${nuclearReactorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:nuclearReactorInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/nuclearReactor/edit.gsp
<%@ page import="com.nuclearreactor.reactor.NuclearReactor" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'nuclearReactor.label', default: 'NuclearReactor')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-nuclearReactor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-nuclearReactor" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${nuclearReactorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${nuclearReactorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:nuclearReactorInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${nuclearReactorInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/nuclearReactor/index.gsp
<%@ page import="com.nuclearreactor.reactor.NuclearReactor" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'nuclearReactor.label', default: 'NuclearReactor')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-nuclearReactor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-nuclearReactor" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="nuclearReactor.company.label" default="Company" /></th>
					
						<g:sortableColumn property="code" title="${message(code: 'nuclearReactor.code.label', default: 'Code')}" />
					
						<g:sortableColumn property="lastUpdate" title="${message(code: 'nuclearReactor.lastUpdate.label', default: 'Last Update')}" />
					
						<g:sortableColumn property="pumpState" title="${message(code: 'nuclearReactor.pumpState.label', default: 'Pump State')}" />
					
						<g:sortableColumn property="rodsState" title="${message(code: 'nuclearReactor.rodsState.label', default: 'Rods State')}" />
					
						<g:sortableColumn property="heaterState" title="${message(code: 'nuclearReactor.heaterState.label', default: 'Heater State')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${nuclearReactorInstanceList}" status="i" var="nuclearReactorInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${nuclearReactorInstance.id}">${fieldValue(bean: nuclearReactorInstance, field: "company")}</g:link></td>
					
						<td>${fieldValue(bean: nuclearReactorInstance, field: "code")}</td>
					
						<td><g:formatDate date="${nuclearReactorInstance.lastUpdate}" /></td>
					
						<td>${fieldValue(bean: nuclearReactorInstance, field: "pumpState")}</td>
					
						<td>${fieldValue(bean: nuclearReactorInstance, field: "rodsState")}</td>
					
						<td>${fieldValue(bean: nuclearReactorInstance, field: "heaterState")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${nuclearReactorInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>