grails-app/domain/com/nuclearreactor/reactor/NuclearReactorConfiguration.groovy
package com.nuclearreactor.reactor

class NuclearReactorConfiguration {

    String getReactorInfoURL
    String getTemperatureURL
    String setValveStateURL
    String setRodsStateURL
    String setPumpStateURL
    String setHeaterStateURL



    static belongsTo = [
            nuclearReactor : NuclearReactor
    ]
    static constraints = {
        getReactorInfoURL nullable: true, blank: false
        getTemperatureURL nullable: true, blank: false
        setValveStateURL nullable: true, blank: false
        setRodsStateURL nullable: true, blank: false
        setPumpStateURL nullable: true, blank: false
        setHeaterStateURL nullable: true, blank: false
        nuclearReactor nullable: false
    }

}

grails-app/controllers/com/nuclearreactor/reactor/NuclearReactorConfigurationController.groovy
package com.nuclearreactor.reactor

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class NuclearReactorConfigurationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def index(Integer max) {
        redirect(action: 'show', id: NuclearReactor.findByCode("2XD1AS").configuration.id)
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def show(NuclearReactorConfiguration nuclearReactorConfigurationInstance) {
        respond nuclearReactorConfigurationInstance
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    def edit(NuclearReactorConfiguration nuclearReactorConfigurationInstance) {
        respond nuclearReactorConfigurationInstance
    }

    @Secured(['ROLE_ADMIN', 'ROLE_ADMIN_NUCLEAR_REACTOR', 'ROLE_OPERATOR_NUCLEAR_REACTOR'])
    @Transactional
    def update(NuclearReactorConfiguration nuclearReactorConfigurationInstance) {
        if (nuclearReactorConfigurationInstance == null) {
            notFound()
            return
        }

        if (nuclearReactorConfigurationInstance.hasErrors()) {
            respond nuclearReactorConfigurationInstance.errors, view: 'edit'
            return
        }

        nuclearReactorConfigurationInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'NuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration'), nuclearReactorConfigurationInstance.id])
                redirect nuclearReactorConfigurationInstance
            }
            '*' { respond nuclearReactorConfigurationInstance, [status: OK] }
        }
    }
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'nuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/nuclearReactorConfiguration/_form.gsp
<%@ page import="com.nuclearreactor.reactor.NuclearReactorConfiguration" %>



<div class="fieldcontain ${hasErrors(bean: nuclearReactorConfigurationInstance, field: 'getReactorInfoURL', 'error')} ">
	<label for="getReactorInfoURL">
		<g:message code="nuclearReactorConfiguration.getReactorInfoURL.label" default="Get Reactor Info URL" />
		
	</label>
	<g:textField name="getReactorInfoURL" value="${nuclearReactorConfigurationInstance?.getReactorInfoURL}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorConfigurationInstance, field: 'getTemperatureURL', 'error')} ">
	<label for="getTemperatureURL">
		<g:message code="nuclearReactorConfiguration.getTemperatureURL.label" default="Get Temperature URL" />
		
	</label>
	<g:textField name="getTemperatureURL" value="${nuclearReactorConfigurationInstance?.getTemperatureURL}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorConfigurationInstance, field: 'setValveStateURL', 'error')} ">
	<label for="setValveStateURL">
		<g:message code="nuclearReactorConfiguration.setValveStateURL.label" default="Set Valve State URL" />
		
	</label>
	<g:textField name="setValveStateURL" value="${nuclearReactorConfigurationInstance?.setValveStateURL}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorConfigurationInstance, field: 'setRodsStateURL', 'error')} ">
	<label for="setRodsStateURL">
		<g:message code="nuclearReactorConfiguration.setRodsStateURL.label" default="Set Rods State URL" />
		
	</label>
	<g:textField name="setRodsStateURL" value="${nuclearReactorConfigurationInstance?.setRodsStateURL}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorConfigurationInstance, field: 'setPumpStateURL', 'error')} ">
	<label for="setPumpStateURL">
		<g:message code="nuclearReactorConfiguration.setPumpStateURL.label" default="Set Pump State URL" />
		
	</label>
	<g:textField name="setPumpStateURL" value="${nuclearReactorConfigurationInstance?.setPumpStateURL}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: nuclearReactorConfigurationInstance, field: 'setHeaterStateURL', 'error')} ">
	<label for="setHeaterStateURL">
		<g:message code="nuclearReactorConfiguration.setHeaterStateURL.label" default="Set Heater State URL" />
		
	</label>
	<g:textField name="setHeaterStateURL" value="${nuclearReactorConfigurationInstance?.setHeaterStateURL}"/>

</div>


	<input type="hidden" name="nuclearReactor.id" value="${nuclearReactorConfigurationInstance?.nuclearReactor?.id}"/></div>

grails-app/views/nuclearReactorConfiguration/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'nuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-nuclearReactorConfiguration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-nuclearReactorConfiguration" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${nuclearReactorConfigurationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${nuclearReactorConfigurationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:nuclearReactorConfigurationInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/nuclearReactorConfiguration/edit.gsp
<%@ page import="com.nuclearreactor.reactor.NuclearReactorConfiguration" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'nuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-nuclearReactorConfiguration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-nuclearReactorConfiguration" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${nuclearReactorConfigurationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${nuclearReactorConfigurationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:nuclearReactorConfigurationInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${nuclearReactorConfigurationInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/nuclearReactorConfiguration/index.gsp
<%@ page import="com.nuclearreactor.reactor.NuclearReactorConfiguration" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'nuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-nuclearReactorConfiguration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-nuclearReactorConfiguration" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="getReactorInfoURL" title="${message(code: 'nuclearReactorConfiguration.getReactorInfoURL.label', default: 'Get Reactor Info URL')}" />
					
						<g:sortableColumn property="getTemperatureURL" title="${message(code: 'nuclearReactorConfiguration.getTemperatureURL.label', default: 'Get Temperature URL')}" />
					
						<g:sortableColumn property="setValveStateURL" title="${message(code: 'nuclearReactorConfiguration.setValveStateURL.label', default: 'Set Valve State URL')}" />
					
						<g:sortableColumn property="setRodsStateURL" title="${message(code: 'nuclearReactorConfiguration.setRodsStateURL.label', default: 'Set Rods State URL')}" />
					
						<g:sortableColumn property="setPumpStateURL" title="${message(code: 'nuclearReactorConfiguration.setPumpStateURL.label', default: 'Set Pump State URL')}" />
					
						<g:sortableColumn property="setHeaterStateURL" title="${message(code: 'nuclearReactorConfiguration.setHeaterStateURL.label', default: 'Set Heater State URL')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${nuclearReactorConfigurationInstanceList}" status="i" var="nuclearReactorConfigurationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${nuclearReactorConfigurationInstance.id}">${fieldValue(bean: nuclearReactorConfigurationInstance, field: "getReactorInfoURL")}</g:link></td>
					
						<td>${fieldValue(bean: nuclearReactorConfigurationInstance, field: "getTemperatureURL")}</td>
					
						<td>${fieldValue(bean: nuclearReactorConfigurationInstance, field: "setValveStateURL")}</td>
					
						<td>${fieldValue(bean: nuclearReactorConfigurationInstance, field: "setRodsStateURL")}</td>
					
						<td>${fieldValue(bean: nuclearReactorConfigurationInstance, field: "setPumpStateURL")}</td>
					
						<td>${fieldValue(bean: nuclearReactorConfigurationInstance, field: "setHeaterStateURL")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${nuclearReactorConfigurationInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/nuclearReactorConfiguration/show.gsp
<%@ page import="com.nuclearreactor.reactor.NuclearReactorConfiguration" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'nuclearReactorConfiguration.label', default: 'NuclearReactorConfiguration')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-nuclearReactorConfiguration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">

		</div>
		<div id="show-nuclearReactorConfiguration" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list nuclearReactorConfiguration">
			
				<g:if test="${nuclearReactorConfigurationInstance?.getReactorInfoURL}">
				<li class="fieldcontain">
					<span id="getReactorInfoURL-label" class="property-label"><g:message code="nuclearReactorConfiguration.getReactorInfoURL.label" default="Get Reactor Info URL" /></span>
					
						<span class="property-value" aria-labelledby="getReactorInfoURL-label"><g:fieldValue bean="${nuclearReactorConfigurationInstance}" field="getReactorInfoURL"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${nuclearReactorConfigurationInstance?.getTemperatureURL}">
				<li class="fieldcontain">
					<span id="getTemperatureURL-label" class="property-label"><g:message code="nuclearReactorConfiguration.getTemperatureURL.label" default="Get Temperature URL" /></span>
					
						<span class="property-value" aria-labelledby="getTemperatureURL-label"><g:fieldValue bean="${nuclearReactorConfigurationInstance}" field="getTemperatureURL"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${nuclearReactorConfigurationInstance?.setValveStateURL}">
				<li class="fieldcontain">
					<span id="setValveStateURL-label" class="property-label"><g:message code="nuclearReactorConfiguration.setValveStateURL.label" default="Set Valve State URL" /></span>
					
						<span class="property-value" aria-labelledby="setValveStateURL-label"><g:fieldValue bean="${nuclearReactorConfigurationInstance}" field="setValveStateURL"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${nuclearReactorConfigurationInstance?.setRodsStateURL}">
				<li class="fieldcontain">
					<span id="setRodsStateURL-label" class="property-label"><g:message code="nuclearReactorConfiguration.setRodsStateURL.label" default="Set Rods State URL" /></span>
					
						<span class="property-value" aria-labelledby="setRodsStateURL-label"><g:fieldValue bean="${nuclearReactorConfigurationInstance}" field="setRodsStateURL"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${nuclearReactorConfigurationInstance?.setPumpStateURL}">
				<li class="fieldcontain">
					<span id="setPumpStateURL-label" class="property-label"><g:message code="nuclearReactorConfiguration.setPumpStateURL.label" default="Set Pump State URL" /></span>
					
						<span class="property-value" aria-labelledby="setPumpStateURL-label"><g:fieldValue bean="${nuclearReactorConfigurationInstance}" field="setPumpStateURL"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${nuclearReactorConfigurationInstance?.setHeaterStateURL}">
				<li class="fieldcontain">
					<span id="setHeaterStateURL-label" class="property-label"><g:message code="nuclearReactorConfiguration.setHeaterStateURL.label" default="Set Heater State URL" /></span>
					
						<span class="property-value" aria-labelledby="setHeaterStateURL-label"><g:fieldValue bean="${nuclearReactorConfigurationInstance}" field="setHeaterStateURL"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${nuclearReactorConfigurationInstance?.nuclearReactor}">
				<li class="fieldcontain">
					<span id="nuclearReactor-label" class="property-label"><g:message code="nuclearReactorConfiguration.nuclearReactor.label" default="Nuclear Reactor" /></span>
					
						<span class="property-value" aria-labelledby="nuclearReactor-label"><a href="javascript:void(0)">${nuclearReactorConfigurationInstance?.nuclearReactor as grails.converters.JSON}</a></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:nuclearReactorConfigurationInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${nuclearReactorConfigurationInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
				</fieldset>
			</g:form>
		</div>
	</body>
</html>